### ISSUE TITLE
2FA sayfasının düzeltilmesi lazım

### ISSUE THREAD

**Issue by odest** [GuvendeKal/guvendekal.org#111]
### Son eklenen [2 Faktörlü Doğrulama](https://guvendekal.org/#/2-faktorlu-dogrulama) sayfasında eksiklikler var.  [İlgili PR](https://github.com/GuvendeKal/guvendekal.org/pull/110)

![temp](https://github.com/user-attachments/assets/4d452426-0fdd-4d73-bf48-22b13f37d6c4)

**Comment by Unchanged4352** [comment]
Kendi repomda değişiklikler yaptım 2 ve 3 çözüldü büyük ihtimalle 1'i müsait olduğumda yaparım pcyi kapattım

**Comment by odest** [comment]
@Unchanged4352 Tmmdır

**Comment by GokturkTalha** [comment]
@odest göz ucuyla bakmıştım kontrol etmeden, hata bende. bir kaç haftadır yoğunluğumdan, ailevi ve bazı sağlık sorunlarından ötürü birazcık boşlamıştım ama devam edeceğim.

**Comment by odest** [comment]
@GokturkTalha Estağfurullah hocam, geçmiş olsun. Ben de müsait oldukça bakıyorum.

**Comment by Unchanged4352** [comment]
Şimdi bir bakmışız 2FA kısmı silinmiş falan :D

**Comment by Unchanged4352** [comment]
#112  yine hata ya da eksiklik bulursanız lütfen belirtin gözümden kaçmış olabilir

**Comment by GokturkTalha** [comment]
> #112 yine hata ya da eksiklik bulursanız lütfen belirtin gözümden kaçmış olabilir

Kontrol edeceğim.

**Comment by GokturkTalha** [comment]
Ente-auth logosunu transparan bir haliyle değiştirmeliyiz. Açıklama ve farklı alternatiflerde eklenmesi lazım tabii.

**Comment by Unchanged4352** [comment]
> Ente-auth logosunu transparan bir haliyle değiştirmeliyiz. Açıklama ve farklı alternatiflerde eklenmesi lazım tabii. 
> 
> Şimdilik kalsın, yarın ilgilenmeye çalışacağım. Son yapılan değişikliklerde yetersiz gibi duruyor @Unchanged4352 @islemci 

Sorun bende mi bilmem ama logosunu zar zor bulabildim ben ve sorun şu ki başka alternatif bilmiyorum

**Comment by GokturkTalha** [comment]
> Sorun bende mi bilmem ama logosunu zar zor bulabildim transparan bulamam çok yüksek bir ihtimalle ve sorun şu ki başka alternatif bilmiyorum

Sıkıntı değil bende her kategorideki uygulamaları bilmiyorum genel olarak , topluluk katkısı ile büyüyoruz :) 

Ben logoyu bulamazsak transparan haline geçiririm sıkıntı yok.

**Comment by Unchanged4352** [comment]
Syncthing'i de ben yapim mi senkronizasyon araçları için

**Comment by GokturkTalha** [comment]
> Syncthing'i de ben yapim mi senkronizasyon araçları için

Merhaba yapmak istiyorsanız  yapabilirsiniz hocam

**Comment by Unchanged4352** [comment]
Artık kapatılması gerekmiyor mu @GokturkTalha

**Comment by GokturkTalha** [comment]
> Artık kapatılması gerekmiyor mu @GokturkTalha 

Aslında çekme isteğine eklemiştik kapanmamış garip bir şekilde.
