### ISSUE TITLE
CMS desteği eklenebilir

### ISSUE THREAD

**Issue by Sxinar** [GuvendeKal/guvendekal.org#117]
Selamlar.
Topluluğa faydam olmasını istediğim için GüvendeKal projesinin bir parçası olmak istediğimi belirteyim.
Bu bağlamda Self Host imkanı bulunan ve gizlilik odaklı rehberlerin daha hızlı yazılabilmesini sağlayan PagesCMS sisteme eklenebilir.

Kendi Blog sistemimde PagesCMS kullanmaktayım çok memnunum.
Barındırmak için Cloudflare veya Vercel veya Netlify yeterli.

Kendi barındırdığım CMS adresi:
https://sxinar.pages.dev eğer ssl hatası verirse 5 defa F5 çekmeniz yeterli :D

**Comment by GokturkTalha** [comment]
Ne işe yaradığını çok anlayamadım, karşıma böyle bir ekran çıkıyor;

![Ekran Görüntüsü - 2024-11-13 14-08-30](https://github.com/user-attachments/assets/e3c74c30-3fa2-48f0-a61c-81f067b27ca5)

PegesCMS dediğiniz şeyin olayı bu olabilir gerçi. Ne gibi faydaları olabileceğini pek idrak edemedim, konuyu biraz daha açarsanız daha iyi olur.

**Comment by Sxinar** [comment]
> Ne işe yaradığını çok anlayamadım, karşıma böyle bir ekran çıkıyor;
> 
> ![Ekran Görüntüsü - 2024-11-13 14-08-30](https://private-user-images.githubusercontent.com/128845803/385730899-e3c74c30-3fa2-48f0-a61c-81f067b27ca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTY1NDQsIm5iZiI6MTczMTQ5NjI0NCwicGF0aCI6Ii8xMjg4NDU4MDMvMzg1NzMwODk5LWUzYzc0YzMwLTNmYTItNDhmMC1hNjFjLTgxZjA2N2IyN2NhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMTEwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTYyMmRjNWRkMzAzNDJjMmMxNjM4MmNlOGNkYTFlNTcyOTdhMGU5YjRjNjAwMzNkNDgyYTdiZjUzZGNlZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kejsAjw_0x0-F90LwPWcY-2CQxpHPWmerfMupKGxBJY)
> 
> PegesCMS dediğiniz şeyin olayı bu olabilir gerçi. Ne gibi faydaları olabileceğini pek idrak edemedim, konuyu biraz daha açarsanız daha iyi olur.

Hızlı cevabınız için teşekkür ederim.
Bu sistem github ile giriş yapılan ve repo seçilerek markdown olmadan (İSteğe bağlı olarak markdown da kullanılabilir) yazılar yazabilen ve dosyalar oluşturulan,REsimler eklenebilen bir sistem.

İsterseniz ben size birkaç fotoğraf da ileteyim.
![Ekran görüntüsü 2024-11-13 141310](https://github.com/user-attachments/assets/d3bd6edc-19af-4544-a014-2153bb06c934)
![Ekran görüntüsü 2024-11-13 141342](https://github.com/user-attachments/assets/025e2c47-bdfa-441c-bdb4-3c761efab634)
![Ekran görüntüsü 2024-11-13 141524](https://github.com/user-attachments/assets/952e1702-3799-49dd-9880-71a531270ab1)

**Comment by Sxinar** [comment]
> Docsify ile uyumlu olacağını zannetmiyorum, uyumlu olsa bile anasayfa ve pek çok sayfada html & css & js kullanımlarımız oldu bunları taşıyamayız sanırım.

Evet,bende forkladığım projede yapılandırma dosyası ile denediğimde Yazıların başlığının görünmediğini fark ettim.
