### ISSUE TITLE
Eklenti Önerisi

### ISSUE THREAD

**Issue by thechief77** [GuvendeKal/guvendekal.org#152]
![3402969](https://github.com/user-attachments/assets/23cdeaa9-fcb3-4eb4-93f6-502c73403458)

Dosya ekleyemediğim için sayfaya görselli olarak ekleyemedim düzeni de bozmak istemedik ama mahremiyetine önem veren ancak biraz üşengeç arkadaşlar için ToS;Dr
yani Terms Of Service; Didn't Read. Herkes kullanım sözleşmesi onaylıyor ama kim bunları gerçekten okuyor? Herkes çevresinden duyduğu kadar doğruluğunu araştırmadan bilgi kirliliği yapıyor. Bunun önüne geçmek için geliştirici ekip böyle bir eklenti yayınlamış
Eklentinin yaptığı tarayıcı tepsisine sabitlendiği zaman siteye mahremiyete verdiği önem üzerinden puan vermek.
![image](https://github.com/user-attachments/assets/017db6a9-f9cf-4cb2-a032-3727de746a5c)
(Sağ üstte)
Tıklarsanız da sakıncalı madde ve kısımları size gösteriyor.
https://github.com/tosdr/browser-extensions
Açık kaynaklı olan bu eklentinin kesinlikle eklenti listesinde olması gerektiğini düşünüyorum ancak dediğim gibi kendim ekleyemedim @GokturkTalha  ilgilenirsen sevinirim tekrardan iyi çalışmalar.

**Comment by GokturkTalha** [comment]
Bu eklenti anladığım kadarıyla direkt reddediyor çerez gibi şeyleri yada toplanılan bilgileri doğru muyum?

**Comment by thechief77** [comment]
> Bu eklenti anladığım kadarıyla direkt reddediyor çerez gibi şeyleri yada toplanılan bilgileri doğru muyum?

Hayır, eklenti sadece hizmet koşullarını değerlendiriyor ve sana bir derece veriyor
(Çalışma şekli bir çok kullanıcının hizmet koşullarını okuması, site veritabanına girmesi ve derecelendirilmesi ardından son kullanıcıya ulaşıyor)
Dereceye göre siteye kaydolmak tamamen senin elinde sunduğu şey temiz, anlaşılır ve okunaklı ToS özetleyici.

**Comment by GokturkTalha** [comment]
> > Bu eklenti anladığım kadarıyla direkt reddediyor çerez gibi şeyleri yada toplanılan bilgileri doğru muyum?
> 
> Hayır, eklenti sadece hizmet koşullarını değerlendiriyor ve sana bir derece veriyor (Çalışma şekli bir çok kullanıcının hizmet koşullarını okuması, site veritabanına girmesi ve derecelendirilmesi ardından son kullanıcıya ulaşıyor) Dereceye göre siteye kaydolmak tamamen senin elinde sunduğu şey temiz, anlaşılır ve okunaklı ToS özetleyici.

Tamamdır bunu bir düşünelim hocam, projede biraz yoğunluk var gibi :) Yetişmekte biraz zorlanıyorum.

**Comment by odk-0160** [comment]
Eklenirse güzel olur.TosDr tarayıcı eklentisi olduğundan haberim yoktu ama internet sitesi kesinlikle kullanışlı ve mutlaka siteye eklenmeli.
Sitede(Guvendekal.org) Güvenlik sayfasında güvenlik için yararlı bağlantılar kısmı bulunuyor.
Bahsi geçen TosDr.org sitesi de Mahremiyet sayfasında mahremiyet için yararlı bağlantılar kısmına eklenebilir.
İnternet sitelerinin hizmet şartlarını kullanım koşullarını tırtıklanan verileri vs. derleyip kategorilendirip sunuyor
uzun karışık privacy policy okumaktan kaçınmak direkt sitenin neler yaptığını gösteriyor
Privacy policylerde belirtilen şartları işlemleri risk ve etkiye göre derecelendiriyor
<img width="1410" alt="Ekran Resmi 2024-12-04 21 41 49" src="https://github.com/user-attachments/assets/b0cec98c-f1f5-4955-8ca2-8f313d599bc6">

**Örnek:**
<img width="413" alt="Ekran Resmi 2024-12-04 21 37 02" src="https://github.com/user-attachments/assets/e597217a-9f6b-4470-8e7b-acca1b4bf125">

**Comment by GokturkTalha** [comment]
> Eklenirse güzel olur.TosDr tarayıcı eklentisi olduğundan haberim yoktu ama internet sitesi kesinlikle kullanışlı ve mutlaka siteye eklenmeli. Sitede(Guvendekal.org) Güvenlik sayfasında güvenlik için yararlı bağlantılar kısmı bulunuyor. Bahsi geçen TosDr.org sitesi de Mahremiyet sayfasında mahremiyet için yararlı bağlantılar kısmına eklenebilir. İnternet sitelerinin hizmet şartlarını kullanım koşullarını tırtıklanan verileri vs. derleyip kategorilendirip sunuyor uzun karışık privacy policy okumaktan kaçınmak için direkt sitenin neler yaptığını gösteriyor Privacy policylerde belirtilen şartları işlemleri risk ve etkiye göre topluluk oylarıyla derecelendiriyor <img alt="Ekran Resmi 2024-12-04 21 41 49" width="1410" src="https://private-user-images.githubusercontent.com/78966027/392525319-b0cec98c-f1f5-4955-8ca2-8f313d599bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTE3NjIsIm5iZiI6MTczMzM1MTQ2MiwicGF0aCI6Ii83ODk2NjAyNy8zOTI1MjUzMTktYjBjZWM5OGMtZjFmNS00OTU1LThjYTItOGYzMTNkNTk5YmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyMzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzY5MjJmNjMwNTNmYjZhYWQ4YmQ1ZGE2NDA1YTJhMTkxM2QxOTkzMzIyZWI1YjdmMDUzYzJhYjcxZDQ4MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x3GwgeSZ6qXGPXlCU9GEMDGyHd9pV5iV-kImfn-BpfM">
> 
> **Örnek:** <img alt="Ekran Resmi 2024-12-04 21 37 02" width="413" src="https://private-user-images.githubusercontent.com/78966027/392523761-e597217a-9f6b-4470-8e7b-acca1b4bf125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTE3NjIsIm5iZiI6MTczMzM1MTQ2MiwicGF0aCI6Ii83ODk2NjAyNy8zOTI1MjM3NjEtZTU5NzIxN2EtOWY2Yi00NDcwLThlN2ItYWNjYTFiNGJmMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyMzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYmNmZWViM2YwMjBjMTM1YWY5ZGMzZWFmODk3MzczNTI0YmRiZTIzNmI3YTYzOTY2ZjVmYWJlYmY5NmY2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-R10CGi8qyFf7Hn7Fzk-ZosI_3F-uj5VK93r3VYDkYQ">

> Eklentisi bulunuyor Firefox'da. Kesinlikle ekleyin hocam, bilmemenize üzüldüm sabiylemeyi de unutmayın çok kullanışlı oluyor.

İsteyen birisi varsa ilgili eklentiyi ve eklemeleri yapabilir. Bazı mental sıkıntılarımdan ötürü pek bakamıyorum.

**Comment by odk-0160** [comment]
> > Eklenirse güzel olur.TosDr tarayıcı eklentisi olduğundan haberim yoktu ama internet sitesi kesinlikle kullanışlı ve mutlaka siteye eklenmeli. Sitede(Guvendekal.org) Güvenlik sayfasında güvenlik için yararlı bağlantılar kısmı bulunuyor. Bahsi geçen TosDr.org sitesi de Mahremiyet sayfasında mahremiyet için yararlı bağlantılar kısmına eklenebilir. İnternet sitelerinin hizmet şartlarını kullanım koşullarını tırtıklanan verileri vs. derleyip kategorilendirip sunuyor uzun karışık privacy policy okumaktan kaçınmak için direkt sitenin neler yaptığını gösteriyor Privacy policylerde belirtilen şartları işlemleri risk ve etkiye göre topluluk oylarıyla derecelendiriyor <img alt="Ekran Resmi 2024-12-04 21 41 49" width="1410" src="https://private-user-images.githubusercontent.com/78966027/392525319-b0cec98c-f1f5-4955-8ca2-8f313d599bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTE3NjIsIm5iZiI6MTczMzM1MTQ2MiwicGF0aCI6Ii83ODk2NjAyNy8zOTI1MjUzMTktYjBjZWM5OGMtZjFmNS00OTU1LThjYTItOGYzMTNkNTk5YmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyMzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzY5MjJmNjMwNTNmYjZhYWQ4YmQ1ZGE2NDA1YTJhMTkxM2QxOTkzMzIyZWI1YjdmMDUzYzJhYjcxZDQ4MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x3GwgeSZ6qXGPXlCU9GEMDGyHd9pV5iV-kImfn-BpfM">
> > **Örnek:** <img alt="Ekran Resmi 2024-12-04 21 37 02" width="413" src="https://private-user-images.githubusercontent.com/78966027/392523761-e597217a-9f6b-4470-8e7b-acca1b4bf125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTE3NjIsIm5iZiI6MTczMzM1MTQ2MiwicGF0aCI6Ii83ODk2NjAyNy8zOTI1MjM3NjEtZTU5NzIxN2EtOWY2Yi00NDcwLThlN2ItYWNjYTFiNGJmMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyMzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYmNmZWViM2YwMjBjMTM1YWY5ZGMzZWFmODk3MzczNTI0YmRiZTIzNmI3YTYzOTY2ZjVmYWJlYmY5NmY2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-R10CGi8qyFf7Hn7Fzk-ZosI_3F-uj5VK93r3VYDkYQ">
> 
> > Eklentisi bulunuyor Firefox'da. Kesinlikle ekleyin hocam, bilmemenize üzüldüm sabiylemeyi de unutmayın çok kullanışlı oluyor.
> 
> İsteyen birisi varsa ilgili eklentiyi ve eklemeleri yapabilir. Bazı mental sıkıntılarımdan ötürü pek bakamıyorum.

Peki hocam.Düzgünce inceledikten sonra eklemek için hazırlık yapmayı düşünüyorum

**Comment by thechief77** [comment]
![image](https://github.com/user-attachments/assets/608ea068-f505-48d8-bd19-6da1550fb013)
Tekrar açıyorum fakat şu satır başını düzeltebilir miyiz hocam daha düzgün durur ardından tekrar kapatabilirsiniz sorunu.

**Comment by GokturkTalha** [comment]
Genel bir düzeltme atacağım yakın zamanda. Bilgilendirme için teşekkürler @thechief77

**Comment by odk-0160** [comment]
> Genel bir düzeltme atacağım yakın zamanda. Bilgilendirme için teşekkürler @thechief77

Genel düzeltme için bir issue açılsın oraya problemleri atalım tek yerde toplarız

Sayfayı hazırlayıp görüntülerken problem görünmüyor normalde.Siteye yüklenince farkettim.
