### ISSUE TITLE
İnternet Tarayıcıları kısmından Ungoogled Chromium Kaldırırsın.

### ISSUE THREAD

**Issue by A11Z16** [GuvendeKal/guvendekal.org#161]
Tarayıcılar kısmından Ungoogled Chromium kaldırırsın çünkü stabil ve kullanışlı bir tarayıcı değil. Onun yerine Zen Browser veya Floorp önerilebilir.

**Comment by GokturkTalha** [comment]
Zaten Zen Browser için bir çekme isteği bulunuyor. #109, ilgili konuda neden eklenmediği yazıldı.

Floorp'a gerek yok çünkü LibreWolf mevcut listede. Aslında tarayıcı sayfasından Firefox, Tor Browser'da kalkabilir. Çünkü Tor browser kullandığımız internete değil onion ağına bağlantıda kullanılıyor. Mullvad Browser'da belki kalkabilir çünkü pek işlevsel bir tarayıcı değil gibi (kullanan görmüyorum). Firefox listede çünkü mobil tarafta eklenti çalıştıran başka bir tarayıcı yok sanırım. Aynı zamanda ilgili sayfada Firefox'u kullanacak kullanıcıların belli başlı ayarlamalar yapması gerektiğinden bahsetmiştik.

**Comment by GokturkTalha** [comment]
Ungoogled Chromium dediğiniz gibi sorunlu sanırım, şimdi yükledim ve sürekli hata veriyor, yüklenmiyor bir şey.

**Comment by A11Z16** [comment]
> Zaten Zen Browser için bir çekme isteği bulunuyor. #109, ilgili konuda neden eklenmediği yazıldı.
> 
> Floorp'a gerek yok çünkü LibreWolf mevcut listede. Aslında tarayıcı sayfasından Firefox, Tor Browser'da kalkabilir. Çünkü Tor browser kullandığımız internete değil onion ağına bağlantıda kullanılıyor. Mullvad Browser'da belki kalkabilir çünkü pek işlevsel bir tarayıcı değil gibi (kullanan görmüyorum). Firefox listede çünkü mobil tarafta eklenti çalıştıran başka bir tarayıcı yok sanırım. Aynı zamanda ilgili sayfada Firefox'u kullanacak kullanıcıların belli başlı ayarlamalar yapması gerektiğinden bahsetmiştik.

Bence Firefox yerine Floorp ekleyebiliriz.

**Comment by GokturkTalha** [comment]
> Bence Firefox yerine Floorp ekleyebiliriz.

Floorp mobili desteklemiyor. Dediğim gibi, mobil tarafta Firefox alternatifsiz biraz.
