### ISSUE TITLE
Mesajlaşma uygulamaları önerisi (Rocket.chat)

### ISSUE THREAD

**Issue by odk-0160** [GuvendeKal/guvendekal.org#179]
Açık kaynaklı özgür bir mesajlaşma platformu olan gizlilik ve güvenlik odaklı topluluklar için geliştirilmiş Rocket Chat siteye eklenebilir.Güvende Kal’a uygun olduğunu düşündüğüm Roket Chat hem bireysel hem de kurumsal olarak güvenli bir alternatif

Platforma pek hakim olmadığım için kendim request atarak düzenleme yapmayı değil öneri yapmayı tercih ettim:

https://github.com/RocketChat/Rocket.Chat

**Comment by GokturkTalha** [comment]
#168

Çekinmenize gerek yok, katkı yaptıkça yazılarınız iyileşecektir. Şuan aktif bir mesajlaşma uygulaması pr'ı var. Dediğiniz uygulama yada site gerçekten güzel ise eklemeyi yaparız. Bira yoğunum kontrol edeceğim.
