### ISSUE TITLE
Arama motorlarına Ecosia'yı ekleme

### ISSUE THREAD

**Issue by A11Z16** [GuvendeKal/guvendekal.org#182]
Bence arama motorlarına Ecosia eklenmeli.

**Comment by GokturkTalha** [comment]
#163 'de neden eklenmediği açıklandı. Siz neden eklenmesi gerektiğini düşünüyorsunuz? Eğer açıklarsanız ve açıklama tatmin ederse ekleriz.

**Comment by A11Z16** [comment]
> #163 'de neden eklenmediği açıklandı. Siz neden eklenmesi gerektiğini düşünüyorsunuz? Eğer açıklarsanız ve açıklama tatmin ederse ekleriz.

Anladım teşekkürler.
