### ISSUE TITLE
Kategori önerisi

### ISSUE THREAD

**Issue by odk-0160** [GuvendeKal/guvendekal.org#184]
Sitede güvenlik için faydalı android toollarını paylaşmak için uygun bir kategori olmadığını düşünüyorum.
günlük hayatta sıklıkla kullanılan platformlar için öncelik veriliyor ki internet güvenliği için önceliğin bu olması önemli ve doğru.

ancak linksheet isimli faydalı bir tool var.Bağlantıları uygulamalara yönlendirmek için kullanılıyor.
Bunu yaparken -uygulamalara yönlendirirken- bağlantılardaki trackerları vs. temizliyor.Uygulamalara veri gönderilmesini önlüyor.(Geçtiğimiz günlerde ekleme önerisinde bulunduğum ClearURLs'i içeriyor.)
İşletim sisteminin varsayılan bağlantı yönlendirmesine alternatif olarak kullanılabilir.
Bunu eklemek için çekme isteği gönderecektim ancak eklemek için kategori seçme konusunda kararsız kaldım.
Sizlerin görüşüne sunayım dedim.

**Comment by GokturkTalha** [comment]
@odk-0160 Merhaba, İşletim Sistemi kategorisinde Windows Güvenliği gibi bir sayfamız mevcut. Aynı zamanda Android kısmıda mevcut. Android kısmına eklenebilir belki.

**Comment by odk-0160** [comment]
Kategori ismi İşletim sistemi olduğu için Custom Romlar vs. ekleneceğini düşünmüştüm

**Comment by GokturkTalha** [comment]
> Kategori ismi İşletim sistemi olduğu için Custom Romlar vs. ekleneceğini düşünmüştüm

Bende öyle düşünüyordum ancak custom rom baya teknik bilgi gerektiren bir şey. O yüzden ileride ekstra custom rom eklersek Android Güvenliği diye bir sayfada açılır. Zaten Windows Güvenliği sayfası var, benzer şeyler.
