### ISSUE TITLE
Arama özelliğinde sorun var

### ISSUE THREAD

**Issue by odk-0160** [GuvendeKal/guvendekal.org#186]
Herhangi bir harfi arama çubuğuna yazarken previewda değil markdownun kodunda arama yapıyor
Bu yüzden koddaki elementler vs. de arama sonuçlarında çıkıyor
<img width="266" alt="bkz. screenshot" src="https://github.com/user-attachments/assets/c6c81b43-b237-4834-a73c-828836782f31">

**Comment by islemci** [comment]
Halihazırda konu hakkında açılmış bir issue var zaten, yenisini açmadan kontrol ederseniz seviniriz.

#100

**Comment by odk-0160** [comment]
Hata ettim.Bundan sonra dikkat edeceğim

**Comment by GokturkTalha** [comment]
> Hata ettim.Bundan sonra dikkat edeceğim

Sorun değil, karşılaştığınız bir hatayı düzeltmeye çalıştığınız ve bildirdiğiniz için biz teşekkür ederiz.
