### ISSUE TITLE
Eklenecekler Listesi

### ISSUE THREAD

**Issue by GokturkTalha** [GuvendeKal/guvendekal.org#2]
Aşağıya eklenmesi gerek kategorileri, sayfaları yada listeleri belirtebilirsiniz.

- Dosya saklama/aktarma
- Dosya şifreleme
- Tarayıcı eklentileri
- İşletim sistemleri
- Yapay zeka
- Çeviri araçları

- Tor kullanımı
- TailsOS
- Mullvad Browser

- Uzak durulması gerekenler

**Comment by GokturkTalha** [comment]
@islemci

**Comment by islemci** [comment]
> Dosya şifreleme
> Tarayıcı eklentileri

Bunu yaparım akşama doğru.

**Comment by Techmolitude** [comment]
Arkadaşlar selam dilerseniz bende sizlere katkıda bulunmak isterim. Mail servisleri kısmını doldurmayı düşünüyorum izniniz olursa

**Comment by 2013dogumeymen** [comment]
- açık kaynak nedir?
- git nedir?
- işletim sistemi nedir?

**Comment by islemci** [comment]
@Techmolitude buyrun efendim, isteyen herkes katkıda bulunabilir zaten. 😀

**Comment by GokturkTalha** [comment]
> Arkadaşlar selam dilerseniz bende sizlere katkıda bulunmak isterim. Mail servisleri kısmını doldurmayı düşünüyorum izniniz olursa

Merhaba tabii ki isteyen herkes katılabilir :)

**Comment by Techmolitude** [comment]
Umarım topluma farkındalık kazandırabiliriz

**Comment by GokturkTalha** [comment]
> * açık kaynak nedir?
> 
>     * git nedir?
> 
>     * işletim sistemi nedir?

"Açık kaynak", Başlangıç'ın altına Mahremiyet ve Gizliliğin üstüne alınabilir. İçinde neden açık kaynak uygulamalar desteklenmeli/kullanılmalı temalı bir makale yazılabilir

**Comment by islemci** [comment]
> git nedir?

herhangi bir kategoriye sokamayız bence sitede.

**Comment by GokturkTalha** [comment]
- Self-host 
- Dosya dönüştürme
- Dosya sıkıştırma
- Youtube alternatifleri? 

-  Proxy nedir- VPN ile farkları diye bir makale yazılabilir gibi

**Comment by GokturkTalha** [comment]
- Kullanılması gereken tarayıcı eklentileri sayfası eklenecek 

- İşletim sistemleri kategori açılacak

**Comment by relliv** [comment]
> > git nedir?
> 
> herhangi bir kategoriye sokamayız bence sitede.

Küçük bir sözlük sayfası olabilir. Zaman ilerledikçe terimler artmaya başlayacaktır.

**Comment by islemci** [comment]
Sözlük olursa eklenebilir ama git terimi daha çok geliştirici aracı kategorisine girer, yani kullanıcıların bilmesine gerek var mı emin değilim.

**Comment by GokturkTalha** [comment]
> > > git nedir?
> > 
> > 
> > herhangi bir kategoriye sokamayız bence sitede.
> 
> Küçük bir sözlük sayfası olabilir. Zaman ilerledikçe terimler artmaya başlayacaktır.

küçük  bir sözlük sayfası eklenebilir evet, güvenlik ve mahremiyet konularında sözcükleri açıklayabiliriz (brute force, http, anonimite vs)

yinede hâlâ git konusu konsept olarak farklı.
