### ISSUE TITLE
Logo is not dynamic

### ISSUE THREAD

**Issue by odest** [GuvendeKal/guvendekal.org#20]
Güncel logo beyaz renk ile yazılmış bir .png dosyası olduğu için, web sitesinin teması değiştiğinde ve beyaz temaya geçildiğinde logo görünmüyor. Çünkü ikisi de beyaz.

Logo svg yapılabilir ya da hem siyah hem beyaz logo eklenebilir.
Logoyu tasarlarken kullandığınız font ismini söylerseniz, svg olarak yapmayı deneyebilirim?

**Comment by GokturkTalha** [comment]
Logoyu SVG formatında siyah/beyaz olarak docs klasörüne ekledim.

https://github.com/GuvendeKal/guvendekal.org/commit/8626e01a5f47e49d4152d703126b937ea8639b20

Düzenleyebilirsiniz.

**Comment by odest** [comment]
@GokturkTalha, teşekkürler

yarın bakacağım
