### ISSUE TITLE
Açık kaynak sayfasının yeniden yazılması

### ISSUE THREAD

**Issue by islemci** [GuvendeKal/guvendekal.org#25]
İlgili pull: #13

İçerik ve düzen olarak hatalı. Sadece lisans tanıtılmamalı, açık kaynak kavramı anlatılmalıdır.

# ve > tagları doğru kullanılmalıdır. (**_VPN sayfası örnektir!_**)

**Comment by GokturkTalha** [comment]
@2013dogumeymen
