### ISSUE TITLE
404

### ISSUE THREAD

**Issue by GokturkTalha** [GuvendeKal/guvendekal.org#31]
@odest hocam custom 404 page ekleme şansımız var mı, docsify sistemini iyi bildiğinizi düşündüğümden size sormak istedim

**Comment by odest** [comment]
@GokturkTalha ekledim hocam, bir bak  istersen.

![ss](https://github.com/user-attachments/assets/a5ae4f45-ffdb-4b6c-9a03-a366536f6295)

**Comment by GokturkTalha** [comment]
@odest elinize sağlık teşekkürler hocam.
