### ISSUE TITLE
Table Of Content hataları

### ISSUE THREAD

**Issue by GokturkTalha** [GuvendeKal/guvendekal.org#46]
<img width="1440" alt="231341632-81012165-d570-4485-8d34-9c2cabe45f79-2830025661" src="https://github.com/user-attachments/assets/a1a9b973-fa14-48fe-9898-607103b04175">

<img width="1238" alt="snapshot" src="https://github.com/user-attachments/assets/8bcaa154-a846-4d06-a65f-d3708ff131b5">

Sağda bulunan Table Of Content gibi şeyler eklemeye çalıştım ancak beceremedim. @odest rica etsem, eğer biliyorsanız müsait olduğunuzda yardımcı olma şansınız var mı?

**Comment by odest** [comment]
Hemen bakıyorum hocam

**Comment by odest** [comment]
@GokturkTalha, şu siteye baksana: [ligmatv.is-a.dev](https://ligmatv.is-a.dev/#/)
Böyle bir şey yapılabilir mi?

Ben çok uğraşamadım kusura bakma, anca bu örneği buldum.
Yarın vaktim olursa ilgileneceğim.

**Comment by GokturkTalha** [comment]
> @GokturkTalha, şu siteye baksana: [ligmatv.is-a.dev](https://ligmatv.is-a.dev/#/) Böyle bir şey yapılabilir mi?
> 
> Ben çok uğraşamadım kusura bakma, anca bu örneği buldum. Yarın vaktim olursa ilgileneceğim.

sıkıntı yok hocam bende araştırıyorum

**Comment by GokturkTalha** [comment]
Ekledim ancak bazı sorunlarımız mevcut.

1. Toc başlığı "Contents" değiştiremiyoruz.
2. H2'den sonra ki başlıklar Toc'a gelmiyor (Fixlemek için bazı H3 ve sonra ki başlıkları H2'e çevirdim)
3. https://guvendekal.org/#/internet-tarayicilari  gibi başlıkta icon olanlarda toc'da da icon çıkıyor, tocda icon çıkmasını engellemek lazım yada başlıklarda icon kullanmayacağız gibi duruyor.

@odest müsait olunca bakmak istersen iyi olur, benim bilgimi aşıyor gibi ancak araştırıyorum.
