### ISSUE TITLE
Harici sayfalara linkleme yapma

### ISSUE THREAD

**Issue by relliv** [GuvendeKal/guvendekal.org#94]
Bu dökümantasyonun hedef kitlesinin bir aralığı var mı? Eğer bir ev kullanıcısı bu dökümanı ziyaret ediyorsa yine bu dökümantasyon tarafından güvenili kaynaklar ve linkler sağlaması gerektiğini düşünüyorum.

Örneğin https://guvendekal.org/#/tarayici-eklentileri sayfasında sadece eklentilerin listesi sunulmuş. Son kullanıcı bu sayfayı ziyaret edip ismini kopyala yapıştır ile arama motorlarında aratabilir ancak arama motorlarının gösterdiği sonuçlar manipüle edilebilir, kullanıcı reklamlara tıklayabilir veya çok benzer isimlerde domainler veya isimler (*eklenti mağazasında arattığında vs*) karışıklığa yol açabilir. Bu tip anlık sorunları önlemek adına daha kolay ve güvenli bir kaynak olarak linkleri dökümantasyon sağlamalı.

Böylece daha erişilebilir bir kaynak oluşturabiliriz.

**Comment by GokturkTalha** [comment]
Hedef kitlesi genel olarak sanal ortamda mahremiyet ve güvenliğine önem veren kullanıcılar diyebiliriz.

![Ekran Görüntüsü - 2024-10-25 23-49-45](https://github.com/user-attachments/assets/1b3d21aa-1d9c-4cfc-9961-74f0c16563d1)

![Ekran Görüntüsü - 2024-10-25 23-50-52](https://github.com/user-attachments/assets/679e0a54-8cbb-440b-b599-f2f8a162699b)

[VPN Servisleri](https://guvendekal.org/#/vpn) yada [E-posta Servisleri](https://guvendekal.org/#/posta-servisleri)'nde dediğiniz gibi verilen haberlere ve bilgilere kaynak ekledim ve bu gibi bilgilere kaynak vermeye özen gösteriyorum.

Dediğiniz gibi Tarayıcı Eklentileri sayfasına mağazası olan tarayıcıların indirme bağlantılarını koymamız iyi olabilir, aslında diğer sayfalardagenel olarak önerilen uygulamaların sitelerine link yönlendirmesi yapıyoruz ancak bu sayfaya eklemeyi unutmuşuz. Aslında ben bu sayfayı yaparken aklımdaydı koymak ama koymamışım herhalde (ilk 3 eklentiyi ben eklemiştim, diğer 2 eklenti farklı 2 kişi tarafından eklendi onlarda düzene uyup eklememişler)

Aslında [İçerik Kuralları](https://guvendekal.org/#/icerik-kurallari) sayfasınada "Uygulama önerilerinde uygulamanın linki verilmelidir" olarak yazmışız ama gözden kaçmış demek ki.

Bunu biraz önce açtığım kriter sayfası hakkındaki issues'e ekleyeyim. Kriterlere eklemek iyi olabilir ayrıyetten. #92

**Comment by relliv** [comment]
Tarayıcı eklentilerinin yeterli olduğunu söylemiştiniz ama [tosdr](https://tosdr.org/) gibi eklentilere de açık olmamız gerektiğini düşünüyorum. Belki ayrıca bir başlık veya sayfa altında "olursa iyi olur" veya "yararlı eklentiler" şeklinde paylaşılabilir.

**Comment by GokturkTalha** [comment]
> Tarayıcı eklentilerinin yeterli olduğunu söylemiştiniz ama [tosdr](https://tosdr.org/) gibi eklentilere de açık olmamız gerektiğini düşünüyorum. Belki ayrıca bir başlık veya sayfa altında "olursa iyi olur" veya "yararlı eklentiler" şeklinde paylaşılabilir.

Onu ben söylemedim ama benzer eklentilerin eklenmemesi (uBlock Origin gayet güzel çerezleri vs engelliyor- daha fazla bu tarz eklenti önermeye gerek yok gibi), varsa kaldırmanın iyi olacağını ve güvenlik/mahremiyet dışıda ki eklentileri kaldırmanın iyi olabileceğini düşünüyorum. SponsorBlock eklentisi aslında sadece kullanıcının zamanını kurtarmaya yönelik bir eklenti. Güvenlik yada mahremiyet tarafında bir geliştirme yapmıyor.

Sonuç olarak kamu yararına olan bütün eklentileri önerebiliriz ancak benzer yada aynı işlevi gören eklentileri yüklemek gereksiz olabilir.

**Comment by cosmos-emissary** [comment]
Linkler eklendi ve pr olarak gönderildi
